Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -33,10 +33,13 @@ jobs:
       - name: Extract version from JS
         id: get_version
         run: |
-          VERSION=$(sed -n 's/^export const version = "\([^"]*\)"$/\1/p' ./src/main.js)
+          VERSION=$(sed -n 's/^export const version *= *"\([^"]*\)".*$/\1/p' ./src/main.js)
+          if [ -z "$VERSION" ]; then
+            echo "Version extraction failed!"
+            exit 1
+          fi
           echo "version=$VERSION" >> $GITHUB_OUTPUT
           echo "Extracted version: $VERSION"
-        shell: bash
 
       - name: Release
         uses: softprops/action-gh-release@v2
